Delete profile
clowder-cloud/frontend pull request #15
Opened 2024-11-26 10:35 UTC by mizamidou

2024-11-26 11:08 UTC, stevelw requested changes
Great work - some things to fix but it's looking good.

2024-11-26 12:23 UTC, mizamidou commented
I have done the changes. Please check

2024-11-26 14:54 UTC, stevelw requested changes

2024-11-26 14:54 UTC, stevelw commented on src/Components/CatProfile.tsx
> +const loggedInUser = 'loggedInUser';
Should be `USER1` or some other user in the dev database.

2024-11-26 14:54 UTC, stevelw commented on src/Components/CatProfile.tsx
> +		getCatsProfiles('loggedInUser').then((fetchedProfiles) => {
This is a string, not the variable from line 9

2024-11-26 14:54 UTC, stevelw commented on src/Components/CatProfile.tsx
> +		deleteCatProfile('loggedInUser')
Same issue

2024-11-26 14:54 UTC, stevelw commented on src/Components/CatProfile.tsx
> +					${message === 'Failed to delete the profile' ? 'text-red-950' : ''}`}
All styling should be in components now. See `src/Components/Styling/FormElement.tsx` for an example.

2024-11-26 14:54 UTC, stevelw commented on package.json
> +		"socket.io": "^4.8.1",
Not sure why these packages are needed? I don't see them used in the code.

2024-11-27 07:51 UTC, stevelw commented on src/Components/CatProfile.tsx
> +					${message === 'Failed to delete the profile' ? 'text-red-950' : ''}`}
Components are now in #17 awaiting merging to main

2024-11-27 10:06 UTC, stevelw commented on src/Components/CatProfile.tsx
> +		getCatsProfiles('USER1').then((fetchedProfiles) => {
The version I can see on the PR is using a literal string not the variable.

2024-11-27 10:08 UTC, stevelw commented on src/Components/CatProfile.tsx
> +		deleteCatProfile('USER1')
As with the other one, still showing as a literal string in the PR.

2024-11-27 10:10 UTC, stevelw commented on src/Components/CatProfile.tsx
> +const loggedInUser = 'loggedInUser';
I just checked the current seed data, and we're currently seeding with `user1` in lowercase.

2024-11-27 10:11 UTC, stevelw commented on src/Components/CatProfile.tsx
> +		getCatsProfiles('loggedInUser').then((fetchedProfiles) => {
Save case issue as the comment.

2024-11-27 10:12 UTC, stevelw commented on src/Components/CatProfile.tsx
> +		deleteCatProfile('loggedInUser')
Same variable issue as the other comment.

2024-11-27 10:13 UTC, stevelw commented on src/Components/CatProfile.tsx
> +					${message === 'Failed to delete the profile' ? 'text-red-950' : ''}`}
Todo in CL-119

2024-11-27 11:36 UTC, stevelw commented on src/Components/CatProfile.tsx
> +const loggedInUser = 'loggedInUser';
The version I can see still says `USER1`?

2024-11-27 11:38 UTC, stevelw requested changes
Just the username definition issue with the case

2024-11-27 11:41 UTC, jeepies requested changes

2024-11-27 11:41 UTC, jeepies commented on src/Components/CatProfile.tsx
> +const loggedInUser = 'USER1';
Remove this line and change it for something like `const { REACT_APP_LOGGED_IN_USER } = process.env`

2024-11-27 11:41 UTC, jeepies commented on src/Components/CatProfile.tsx
> +		getCatsProfiles(loggedInUser).then((fetchedProfiles) => {
Change the loggedInUser variable to `REACT_APP_LOGGED_IN_USER`

2024-11-27 11:56 UTC, merged