Cl 5 view cats location
clowder-cloud/frontend pull request #4
Opened 2024-11-19 11:41 UTC by PhilTBatt

2024-11-20 09:41 UTC, stevelw commented on src/App.tsx
> +	]);
I assume this is test data? If so, it should be encapsulated (in a different file)

2024-11-20 09:44 UTC, mizamidou approved these changes

2024-11-20 09:55 UTC, PhilTBatt commented on src/App.tsx
> +import React, { useState } from 'react';
React must be in scope

2024-11-20 16:59 UTC, stevelw requested changes

2024-11-20 16:59 UTC, stevelw commented on package.json
> +		"tailwindcss": "^3.4.15"
Tailwind is a dev dependency - it compiles into normal CSS during build

2024-11-21 11:31 UTC, stevelw approved these changes

2024-11-21 11:31 UTC, merged